replicaCount: 1

image:
  repository: phntom/kochi
  tag: 1.1.0
  pullPolicy: IfNotPresent

rbac:
  create: true

service:
  port: 443

#iamRole: arn:aws:iam::123456789000:role/some-role

#aws:
#  eks:
#    role: arn:aws:iam::123456789000:role/some-role