apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "iam-role-manager.fullname" . }}
  labels:
    control-plane: {{ template "iam-role-manager.fullname" . }}
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: {{ template "iam-role-manager.fullname" . }}
      controller-tools.k8s.io: "1.0"
  serviceName: {{ template "iam-role-manager.fullname" . }}
  template:
    metadata:
      labels:
        control-plane: {{ template "iam-role-manager.fullname" . }}
        controller-tools.k8s.io: "1.0"
      {{- if .Values.iamRole}}
      annotations: 
        iam.amazonaws.com/role: {{ .Values.iamRole }}
      {{- end}}
    spec:
    {{- if .Values.rbac.create }}
      serviceAccountName: {{ template "iam-role-manager.fullname" . }}
    {{- end }}
      containers:
      - command:
          - /root/manager
        volumeMounts:
        - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
          name: aws-iam-token
          readOnly: true
        image: '{{ .Values.image.repository }}:{{ .Chart.AppVersion }}'
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ template "iam-role-manager.fullname" . }}
        env:
          - name: AWS_ROLE_ARN
            value: {{ .Values.aws.eks.role }}
          - name: AWS_WEB_IDENTITY_TOKEN_FILE
            value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
          - name: AWS_ROLE_SESSION_NAME
            value: kochi
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
      volumes:
        - name: aws-iam-token
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  audience: sts.amazonaws.com
                  expirationSeconds: 86400
                  path: token
      terminationGracePeriodSeconds: 10
